### PR TITLE
Add correct filename

### PR DESCRIPTION
**Pull request by mrueg**
We can either drop the -timetable or add it to hacs.json this way. @vas3k any preferences?

### CODE REVIEW

**Comment by vas3k** [comment]
Let's drop '-timetable', there's no point in using it anymore

**Comment by mrueg** [comment]
@vas3k Okay, changed it. I also dropped the hassfest workflow since this doesn't work on cards/plugins (my bad)

**Comment by mrueg** [comment]
aah, one more thing: can you rename the repository to "lovelace-berlin-transport-card" @vas3k?  

HACS is very picky: https://hacs.xyz/docs/publish/plugin#example :sweat:

**Comment by vas3k** [comment]
Ok, done

**Comment by mrueg** [comment]
Sweet, it's working!

**Pull request merged**
